# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e07cb083f91fe2344dc0e33ae06f9f1a9ffbaee4bc6ed480a16bb6c2799356fa379a7999f80f64fa49b5250aedc2abeb8163b66f6d20746841370625fc4467e

test:
  secret_key_base: acc68d038dc26c0a98a3a9a0b9c51e7e21ca7042b4e1551b310be3e907d9e4f50e6145932721c4bc2aa802e5174349862309bf9d0e42cede1b3a7d0a4570680d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
